import { ICategoryItem, IPackageItem } from "./interfaces/IPacakges";

export const categoriesData: ICategoryItem[] = [
  {
    _id: "68052f869696485ca865de53",
    name: "hello 1",
    slug: "hello-1",
    description: "test hello 1",
    icon: "https://zingvel-partner.s3.us-east-1.amazonaws.com/other/a8e1d8b1-cf9e-49cb-a667-27dc2a303b48/passport-1745170297167.png/dc8318e5-c127-4879-a982-59a2134ab8fd",
    isTrending: true,
    createdAt: "2025-04-20T17:31:50.445Z",
    updatedAt: "2025-04-20T17:31:50.445Z",
  },
  {
    _id: "68052f989696485ca865de54",
    name: "zzz ahsdb",
    slug: "zzz-ahsdb",
    description: "zzz ahsdb",
    icon: "https://zingvel-partner.s3.us-east-1.amazonaws.com/other/a8e1d8b1-cf9e-49cb-a667-27dc2a303b48/passport-1745170322002.png/a3c440ec-899b-4a4d-8608-6a011abd4a3f",
    isTrending: true,
    createdAt: "2025-04-20T17:32:08.523Z",
    updatedAt: "2025-04-20T17:32:08.523Z",
  },
  {
    _id: "6807bdee52ead49a63dfd06b",
    name: "abd test",
    slug: "abd-test",
    description: "test abd new",
    icon: "https://zingvel-partner.s3.us-east-1.amazonaws.com/other/10bee112-4b23-4281-9ad1-703d93e6d39c/passport-1745337828036.png/48c59867-17d5-417f-9a3f-af34841ba8e0",
    isTrending: false,
    createdAt: "2025-04-22T16:03:58.408Z",
    updatedAt: "2025-04-25T13:36:31.617Z",
  },
  {
    _id: "6807be0f52ead49a63dfd06c",
    name: "asndas",
    slug: "asndas",
    description: "ansdalsndla",
    icon: "https://zingvel-partner.s3.us-east-1.amazonaws.com/other/10bee112-4b23-4281-9ad1-703d93e6d39c/passport-1745337866741.png/6aea4c69-de22-4f20-a2e0-d063c7739f16",
    isTrending: false,
    createdAt: "2025-04-22T16:04:31.975Z",
    updatedAt: "2025-04-22T16:04:31.975Z",
  },
  {
    _id: "680b8ff23c92e97378fc0707",
    name: "Zingvel",
    slug: "zingvel",
    description: "sdasdad",
    icon: "https://zingvel-partner.s3.us-east-1.amazonaws.com/other/10bee112-4b23-4281-9ad1-703d93e6d39c/instagram-1745588198873.png/62d362c2-509e-49ad-9287-e9b396fc1bdb",
    isTrending: false,
    createdAt: "2025-04-25T13:36:50.424Z",
    updatedAt: "2025-04-25T13:36:50.424Z",
  },
];

export const packagesData: IPackageItem[] = [
  {
    _id: "67e7962972128c2171752d43",
    name: "Lavania package",
    description: "Lavania has the best pacakge",
    location: {
      city: "Mathura",
      state: "Uttar Pradesh",
      country: "India",
      googlePlaceId: "ChIJBVJNPRZxczkRpQ7h752gc0I",
    },
    duration: {
      days: 4,
      nights: 3,
    },
    regularPrice: 2999,
    salePrice: 6999,
    discountedPrice: 7895,
    media: [
      {
        url: "https://zingvel-partner.s3.us-east-1.amazonaws.com/67e7962972128c2171752d43/a8e1d8b1-cf9e-49cb-a667-27dc2a303b48/andrew-deslauriers-oUPywYZT88Y-unsplash-1744055707344.jpg/09fe5e22-3954-4f7d-bc26-7e3530f9f8e3",
        type: "image",
        mediaId: "09fe5e22-3954-4f7d-bc26-7e3530f9f8e3",
      },
    ],
    itinerary: [
      {
        description: "",
        items: [
          {
            type: "accommodation",
            content: "Lavania hotels",
            data: {
              id: "67e795b272128c2171752d42",
              name: "Lavania hotels",
              description: "Lavania has the best hotel",
              location: {
                city: "Mathura",
                state: "Uttar Pradesh",
                country: "India",
                googlePlaceId: "ChIJBVJNPRZxczkRpQ7h752gc0I",
              },
              accommodationType: "resort",
              propertyRatingClass: "5",
              checkIn: "14:00",
              checkOut: "11:00",
              amenities: ["Wi-Fi", "Swimming Pool", "Air Conditioning", "Parking", "Room Service"],
              roomTypes: [
                {
                  name: "Deluxe",
                  capacity: 2,
                  regularPrice: 0,
                  salePrice: 0,
                  discountedPrice: 0,
                  includedMeals: {
                    breakfast: true,
                    lunch: true,
                    dinner: true,
                  },
                  roomMedia: [],
                },
              ],
              media: [],
              price: 5000,
              rating: 0,
              ticketPrice: 0,
              partner_id: "a8e1d8b1-cf9e-49cb-a667-27dc2a303b48",
              createdAt: "2025-03-29T06:39:46.736Z",
              updatedAt: "2025-04-02T15:55:34.010Z",
              published: false,
              status: "active",
              roomType: {
                name: "Deluxe",
                capacity: 2,
                regularPrice: 0,
                salePrice: 0,
                discountedPrice: 0,
                includedMeals: {
                  breakfast: true,
                  lunch: true,
                  dinner: true,
                },
                roomMedia: [],
              },
              vehicleType: null,
            },
          },
        ],
      },
      {
        day: 2,
        description: "",
        activities: [],
        vehicleRentals: [],
        events: [],
        localGuides: [],
        places: [],
        cabs: [],
        buses: [],
        flights: [],
        trains: [],
      },
      {
        day: 3,
        description: "",
        activities: [],
        vehicleRentals: [],
        events: [],
        localGuides: [],
        places: [],
        cabs: [],
        buses: [],
        flights: [],
        trains: [],
      },
      {
        day: 4,
        description: "",
        activities: [],
        vehicleRentals: [],
        events: [],
        localGuides: [],
        places: [],
        cabs: [],
        buses: [],
        flights: [],
        trains: [],
      },
    ],
    inclusions: ["Hotels", "Pickup and drop cabs/Transfers", "Activities", "Flights"],
    exclusions: ["Personal expenses", "Travel insurance", "Additional meals", "Entry fees"],
    customInclusions: [],
    customExclusions: [],
    transferIncluded: true,
    stayIncluded: true,
    breakfastIncluded: false,
    sightseeingIncluded: true,
    rating: 0,
    ticketPrice: 0,
    amenities: [],
    partner_id: "a8e1d8b1-cf9e-49cb-a667-27dc2a303b48",
    createdAt: "2025-03-29T06:41:45.377Z",
    updatedAt: "2025-04-20T17:39:10.757Z",
    published: true,
    id: "67e7962972128c2171752d43",
    status: "active",
    categories: ["67fe8c0ffccd5e3bdedc5c87", "68052f869696485ca865de53", "68052f989696485ca865de54"],
  },
  {
    _id: "67fd0ccf3d946a948abae170",
    name: "Tosh plan",
    description: "qwerfdg",
    location: {
      city: "",
      state: "",
      country: "",
      googlePlaceId: "",
    },
    duration: {
      days: 4,
      nights: 5,
    },
    regularPrice: 10000,
    salePrice: 8000,
    discountedPrice: 7000,
    media: [
      {
        url: "https://zingvel-partner.s3.us-east-1.amazonaws.com/67fd0ccf3d946a948abae170/d6d516b6-ee46-4326-b57e-0fa788e48913/1_desktop_diamond_hero-1744649594426.jpg/36096074-0356-416f-8030-1a727efea568",
        type: "image",
        mediaId: "36096074-0356-416f-8030-1a727efea568",
      },
    ],
    itinerary: [
      {
        description: "jk",
        items: [
          {
            type: "text",
            content: "jk",
          },
        ],
      },
      {
        description: "Test",
        items: [
          {
            type: "text",
            content: "hj",
          },
          {
            type: "text",
            content: "trrths",
          },
        ],
      },
      {
        description: "test",
        items: [],
      },
      {
        description: "Test",
        items: [],
      },
    ],
    inclusions: ["Hotels", "Pickup and drop cabs/Transfers", "Activities", "Events"],
    exclusions: ["Personal expenses", "Additional meals", "Entry fees"],
    customInclusions: ["Bungie jumping", "Safari ride"],
    customExclusions: ["Rafting", "Paragliding"],
    transferIncluded: false,
    stayIncluded: true,
    breakfastIncluded: true,
    sightseeingIncluded: true,
    rating: 0,
    ticketPrice: 0,
    amenities: [],
    partner_id: "d6d516b6-ee46-4326-b57e-0fa788e48913",
    createdAt: "2025-04-14T13:25:35.358Z",
    updatedAt: "2025-04-14T16:53:32.810Z",
    published: true,
    id: "67fd0ccf3d946a948abae170",
    status: "active",
    categories: [],
  },
  {
    _id: "67fd3504bff797ef91d4adbc",
    name: "test pacakge 14-04-21-46",
    description: "asdasdasdjkdcans",
    location: {
      city: "Pune",
      state: "Maharashtra",
      country: "India",
      googlePlaceId: "ChIJARFGZy6_wjsRQ-Oenb9DjYI",
    },
    duration: {
      days: 3,
      nights: 0,
    },
    regularPrice: 4988,
    salePrice: 9889,
    discountedPrice: 8988,
    media: [
      {
        url: "https://zingvel-partner.s3.us-east-1.amazonaws.com/undefined/a8e1d8b1-cf9e-49cb-a667-27dc2a303b48/10-Things-to-Do-in-Shimla-on-Your-Next-Vacation-scaled-e1659280469527-800x530-1744647385906.webp/0a5f59fa-8851-438b-be8e-712c55ef91c0",
        type: "image",
        mediaId: "0a5f59fa-8851-438b-be8e-712c55ef91c0",
      },
    ],
    itinerary: [
      {
        description: "test",
        items: [
          {
            type: "text",
            content: "",
          },
        ],
      },
      {
        description: "test",
        items: [
          {
            type: "text",
            content: "",
          },
        ],
      },
      {
        description: "test",
        items: [
          {
            type: "text",
            content: "",
          },
        ],
      },
    ],
    inclusions: ["Flights", "Activities"],
    exclusions: ["Personal expenses", "Additional meals"],
    customInclusions: [],
    customExclusions: [],
    transferIncluded: true,
    stayIncluded: true,
    breakfastIncluded: true,
    sightseeingIncluded: true,
    rating: 0,
    ticketPrice: 0,
    amenities: [],
    partner_id: "a8e1d8b1-cf9e-49cb-a667-27dc2a303b48",
    createdAt: "2025-04-14T16:17:08.741Z",
    updatedAt: "2025-04-19T11:26:58.964Z",
    published: true,
    categories: ["67fe8c0ffccd5e3bdedc5c87", "67fe8c24fccd5e3bdedc5c88"],
    id: "67fd3504bff797ef91d4adbc",
    status: "active",
  },
  {
    _id: "6804b0fce64757ff07932714",
    name: "Tour to Agra",
    description: "This is a trip to Agra. you will be amazed by TAJ MAHAL",
    location: {
      city: "Agra",
      state: "Uttar Pradesh",
      country: "India",
      googlePlaceId: "ChIJ2UEvfIUNdDkRQjtSqTjvSng",
    },
    duration: {
      days: 1,
      nights: 1,
    },
    media: [],
    itinerary: [
      {
        description:
          "Visit Taj Palace. Visit ZingVel. Visit jhfgsbbsmvnbm. Visit trip. Visit ARGO. Visit svcc. Visit tenning. Tested the text fields.",
        items: [
          {
            type: "accommodation",
            content: "Taj Palace",
            data: {
              id: "67ec292b42bf2a9330b9e0cd",
              name: "Taj Palace",
              description: "sdhjkahd kla hdakh kcn,",
              location: {
                city: "",
                state: "",
                country: "",
                googlePlaceId: "",
              },
              accommodationType: "hotel",
              propertyRatingClass: "3",
              checkIn: "14:00",
              checkOut: "11:00",
              amenities: ["Wi-Fi", "Swimming Pool", "Restaurant", "Gym", "Air Conditioning", "Parking", "Room Service", "Spa", "tstgdb"],
              roomTypes: [
                {
                  name: "delux",
                  capacity: 2,
                  regularPrice: 6,
                  salePrice: 11,
                  discountedPrice: 13,
                  includedMeals: {
                    breakfast: true,
                    lunch: false,
                    dinner: false,
                  },
                  roomMedia: [],
                },
              ],
              media: [
                {
                  type: "video",
                  url: "blob:https://production.dplmafddn5pbd.amplifyapp.com/c0d2fb6c-4b7c-4d87-b306-1e89c4ce66e1",
                },
              ],
              price: 20000,
              rating: 0,
              ticketPrice: 0,
              partner_id: "10bee112-4b23-4281-9ad1-703d93e6d39c",
              createdAt: "2025-04-01T17:58:03.653Z",
              updatedAt: "2025-04-01T17:58:03.653Z",
              published: false,
              roomType: {
                name: "delux",
                capacity: 2,
                regularPrice: 6,
                salePrice: 11,
                discountedPrice: 13,
                includedMeals: {
                  breakfast: true,
                  lunch: false,
                  dinner: false,
                },
                roomMedia: [],
              },
              vehicleType: null,
            },
          },
          {
            type: "activity",
            content: "ZingVel",
            data: {
              id: "67ec294a9bd5a2460bc5f00c",
              name: "ZingVel",
              description: "kfhgsjkfhdhkjhshfkshfkshf kh ksfhksjfdh",
              location: {
                city: "",
                country: "",
              },
              type: "cultural",
              duration: "12",
              pricePerPerson: 0,
              groupSizeLimits: {
                min: 1,
                max: 10,
              },
              requirements: [],
              includedItems: [],
              images: [],
              rating: 0,
              ticketPrice: 0,
              media: [],
              amenities: [],
              partner_id: "10bee112-4b23-4281-9ad1-703d93e6d39c",
              createdAt: "2025-04-01T17:58:34.941Z",
              updatedAt: "2025-04-02T15:55:13.018Z",
              published: false,
              isPublished: false,
              status: "active",
            },
          },
          {
            type: "vehicleRental",
            content: "jhfgsbbsmvnbm",
            data: {
              id: "67ed5a2ea8e07e30dba17877",
              name: "jhfgsbbsmvnbm",
              description: "vsbvs bsm sj fjs vbxmnvbmn",
              location: {
                city: "",
                state: "",
                country: "",
                googlePlaceId: "",
              },
              vehicleTypes: [
                {
                  name: "Ntorque - TVS 150 CC",
                  price: 0,
                  quantity: 1,
                },
              ],
              requiresLicense: true,
              includesInsurance: false,
              price: 0,
              rating: 0,
              ticketPrice: 0,
              media: [],
              amenities: [],
              partner_id: "10bee112-4b23-4281-9ad1-703d93e6d39c",
              createdAt: "2025-04-02T15:39:26.676Z",
              updatedAt: "2025-04-02T15:39:26.676Z",
              published: false,
              roomType: null,
              vehicleType: {
                name: "Ntorque - TVS 150 CC",
                price: 0,
                quantity: 1,
              },
            },
          },
          {
            type: "event",
            content: "trip",
            data: {
              id: "67ed59f70ace956501e02493",
              name: "trip",
              description: "hsfhgsj jhfkjghsfjh ghjsg fjhsb",
              location: {
                city: "",
                state: "",
                country: "",
                googlePlaceId: "",
              },
              type: "festival",
              startDateTime: "2025-04-02T23:08",
              endDateTime: "2025-04-03T21:08",
              capacity: 0,
              pricePerTicket: 0,
              schedule: [],
              amenities: [],
              terms: "",
              media: [
                {
                  type: "video",
                  url: "blob:https://production.dplmafddn5pbd.amplifyapp.com/b7e7fb39-787f-4a2a-b87b-801eabd8f6c2",
                },
              ],
              rating: 0,
              ticketPrice: 0,
              partner_id: "10bee112-4b23-4281-9ad1-703d93e6d39c",
              createdAt: "2025-04-02T15:38:31.709Z",
              updatedAt: "2025-04-02T15:38:31.709Z",
              published: false,
            },
          },
          {
            type: "localGuide",
            content: "ARGO",
            data: {
              id: "67ed5a1482e2f395dba5d501",
              name: "ARGO",
              description: "hgsjfhgsjk gsjf gsfjhgfjsbv",
              bio: "fshgfjhsg jsf jgfj hgfbjvjsbjvbd",
              location: {
                city: "",
                state: "",
                country: "",
                googlePlaceId: "",
              },
              languages: ["hindi"],
              specializations: [],
              experienceYears: 0,
              locationsCovered: [],
              services: [],
              pricing: {
                hourlyRate: 0,
                dailyRate: 0,
              },
              availability: {
                daysAvailable: [],
                timeSlots: [],
              },
              certifications: [],
              images: [],
              status: "active",
              published: false,
              rating: 0,
              ticketPrice: 0,
              media: [],
              amenities: [],
              partner_id: "10bee112-4b23-4281-9ad1-703d93e6d39c",
              createdAt: "2025-04-02T15:39:00.446Z",
              updatedAt: "2025-04-02T15:39:00.446Z",
            },
          },
          {
            type: "place",
            content: "svcc",
            data: {
              id: "67ed5a430ace956501e02494",
              name: "svcc",
              description: "",
              type: "tourist",
              city: "",
              state: "",
              country: "",
              address: "537 BHA / 588",
              rating: 0,
              openingTiming: "9 AM to 5 PM",
              bestTimeToVisit: "October, November, February",
              amenities: [],
              ticketPrice: 0,
              media: [],
              status: "draft",
              published: false,
              location: {
                city: "",
                state: "",
                country: "",
                address: "537 BHA / 588",
              },
              partner_id: "10bee112-4b23-4281-9ad1-703d93e6d39c",
              createdAt: "2025-04-02T15:39:47.336Z",
              updatedAt: "2025-04-02T15:39:47.336Z",
            },
          },
          {
            type: "cab",
            content: "tenning",
            data: {
              id: "67ed5a58d5ef2476058945ff",
              name: "tenning",
              description: "jshf,zcbnm vznb ,nb, nxc,vm",
              vehicleType: "Sedan",
              seatingCapacity: 4,
              pricePerKm: 0,
              minBookingHours: 1,
              availableLocations: [],
              features: [],
              cancellationPolicy: "xdfjgs bvmxn bx vbxmvbvmn",
              driverDetails: {
                provided: true,
                languages: [],
              },
              media: [],
              rating: 0,
              ticketPrice: 0,
              amenities: [],
              partner_id: "10bee112-4b23-4281-9ad1-703d93e6d39c",
              createdAt: "2025-04-02T15:40:08.852Z",
              updatedAt: "2025-04-02T15:40:08.852Z",
              published: false,
            },
          },
          {
            type: "text",
            content: "Tested the text fields.",
          },
          {
            type: "text",
            content: "testing",
          },
        ],
      },
    ],
    inclusions: ["Flights", "Hotels", "Pickup and drop cabs/Transfers", "Activities", "Events"],
    exclusions: ["Personal expenses", "Additional meals", "Optional activities", "Travel insurance"],
    customInclusions: ["test"],
    customExclusions: ["testing"],
    transferIncluded: true,
    stayIncluded: true,
    breakfastIncluded: true,
    sightseeingIncluded: true,
    categories: ["6804b0b0e4e5362bc7bfd3b9", "6807bdee52ead49a63dfd06b", "680b8ff23c92e97378fc0707"],
    rating: 0,
    ticketPrice: 0,
    amenities: [],
    partner_id: "10bee112-4b23-4281-9ad1-703d93e6d39c",
    createdAt: "2025-04-20T08:31:56.277Z",
    updatedAt: "2025-05-20T13:33:48.835Z",
    published: true,
    discountedPrice: 3500,
    id: "6804b0fce64757ff07932714",
    regularPrice: 5000,
    salePrice: 4000,
    status: "active",
  },
  {
    _id: "680b90533c92e97378fc0708",
    name: "asdasd",
    description: "adjasdasjd",
    location: {
      city: "Kasol",
      state: "Himachal Pradesh",
      country: "India",
      googlePlaceId: "ChIJ6TGqdERcBDkRnZRHK-PSEvE",
    },
    duration: {
      days: 2,
      nights: 1,
    },
    regularPrice: 12132,
    salePrice: 12123,
    discountedPrice: 11212,
    media: [
      {
        url: "https://zingvel-partner.s3.us-east-1.amazonaws.com/undefined/10bee112-4b23-4281-9ad1-703d93e6d39c/Screenshot 2025-04-24 at 00.43.41-1745588223597.png/e3021f96-83d0-489f-af3b-9f9a7860c66e",
        type: "image",
        mediaId: "e3021f96-83d0-489f-af3b-9f9a7860c66e",
      },
    ],
    itinerary: [
      {
        description: "sadasdasdasdasd",
        items: [
          {
            type: "accommodation",
            content: "Taj Palace",
            data: {
              id: "67ec292b42bf2a9330b9e0cd",
              name: "Taj Palace",
              description: "sdhjkahd kla hdakh kcn,",
              location: {
                city: "",
                state: "",
                country: "",
                googlePlaceId: "",
              },
              accommodationType: "hotel",
              propertyRatingClass: "3",
              checkIn: "14:00",
              checkOut: "11:00",
              amenities: ["Wi-Fi", "Swimming Pool", "Restaurant", "Gym", "Air Conditioning", "Parking", "Room Service", "Spa", "tstgdb"],
              roomTypes: [
                {
                  name: "delux",
                  capacity: 2,
                  regularPrice: 6,
                  salePrice: 11,
                  discountedPrice: 13,
                  includedMeals: {
                    breakfast: true,
                    lunch: false,
                    dinner: false,
                  },
                  roomMedia: [],
                },
              ],
              media: [
                {
                  type: "video",
                  url: "blob:https://production.dplmafddn5pbd.amplifyapp.com/c0d2fb6c-4b7c-4d87-b306-1e89c4ce66e1",
                },
              ],
              price: 20000,
              rating: 0,
              ticketPrice: 0,
              partner_id: "10bee112-4b23-4281-9ad1-703d93e6d39c",
              createdAt: "2025-04-01T17:58:03.653Z",
              updatedAt: "2025-04-01T17:58:03.653Z",
              published: false,
              roomType: {
                name: "delux",
                capacity: 2,
                regularPrice: 6,
                salePrice: 11,
                discountedPrice: 13,
                includedMeals: {
                  breakfast: true,
                  lunch: false,
                  dinner: false,
                },
                roomMedia: [],
              },
              vehicleType: null,
            },
          },
          {
            type: "activity",
            content: "ZingVel",
            data: {
              id: "67ec294a9bd5a2460bc5f00c",
              name: "ZingVel",
              description: "kfhgsjkfhdhkjhshfkshfkshf kh ksfhksjfdh",
              location: {
                city: "",
                country: "",
              },
              type: "cultural",
              duration: "12",
              pricePerPerson: 0,
              groupSizeLimits: {
                min: 1,
                max: 10,
              },
              requirements: [],
              includedItems: [],
              images: [],
              rating: 0,
              ticketPrice: 0,
              media: [],
              amenities: [],
              partner_id: "10bee112-4b23-4281-9ad1-703d93e6d39c",
              createdAt: "2025-04-01T17:58:34.941Z",
              updatedAt: "2025-04-02T15:55:13.018Z",
              published: false,
              isPublished: false,
              status: "active",
            },
          },
          {
            type: "place",
            content: "noida",
            data: {
              id: "6804aca615132458f3f90527",
              name: "noida",
              description: "dkdjkadjnkajslajdl",
              type: "tourist",
              city: "Jaipur",
              state: "Rajasthan",
              country: "India",
              address: "dszdsa ",
              rating: 5,
              openingTiming: "9 AM to 5 PM",
              bestTimeToVisit: "October, November, February, March",
              amenities: [],
              ticketPrice: 0,
              media: [],
              status: "draft",
              published: false,
              location: {
                city: "Jaipur",
                state: "Rajasthan",
                country: "India",
                address: "dszdsa ",
              },
              partner_id: "10bee112-4b23-4281-9ad1-703d93e6d39c",
              createdAt: "2025-04-20T08:13:26.460Z",
              updatedAt: "2025-04-20T08:13:26.460Z",
            },
          },
          {
            type: "text",
            content: "asdasd",
          },
        ],
      },
      {
        day: 2,
        description: "",
        activities: [],
        vehicleRentals: [],
        events: [],
        localGuides: [],
        places: [],
        cabs: [],
        buses: [],
        flights: [],
        trains: [],
      },
    ],
    inclusions: ["Flights", "Activities"],
    exclusions: ["Personal expenses", "Additional meals"],
    customInclusions: [],
    customExclusions: [],
    transferIncluded: true,
    stayIncluded: true,
    breakfastIncluded: false,
    sightseeingIncluded: false,
    categories: ["68052f989696485ca865de54"],
    rating: 0,
    ticketPrice: 0,
    amenities: [],
    partner_id: "10bee112-4b23-4281-9ad1-703d93e6d39c",
    createdAt: "2025-04-25T13:38:27.556Z",
    updatedAt: "2025-05-31T13:23:07.771Z",
    published: true,
    id: "680b90533c92e97378fc0708",
    status: "active",
  },
  {
    _id: "680cd9948fd593ed72bca280",
    name: "ASDASDASDA",
    description: "",
    location: {
      city: "",
      country: "",
    },
    duration: {},
    media: [],
    itinerary: [],
    inclusions: [],
    exclusions: [],
    customInclusions: [],
    customExclusions: [],
    transferIncluded: false,
    stayIncluded: false,
    breakfastIncluded: false,
    sightseeingIncluded: false,
    rating: 0,
    ticketPrice: 0,
    amenities: [],
    partner_id: "10bee112-4b23-4281-9ad1-703d93e6d39c",
    createdAt: "2025-04-26T13:03:16.424Z",
    updatedAt: "2025-04-26T13:03:19.532Z",
    published: true,
  },
  {
    _id: "680cdb35cc8db47014a875a2",
    name: "molk",
    description: "",
    location: {
      city: "",
      country: "",
    },
    duration: {},
    media: [],
    itinerary: [],
    inclusions: [],
    exclusions: [],
    customInclusions: [],
    customExclusions: [],
    transferIncluded: false,
    stayIncluded: false,
    breakfastIncluded: false,
    sightseeingIncluded: false,
    rating: 0,
    ticketPrice: 0,
    amenities: [],
    partner_id: "10bee112-4b23-4281-9ad1-703d93e6d39c",
    createdAt: "2025-04-26T13:10:13.580Z",
    updatedAt: "2025-04-26T13:10:19.173Z",
    published: true,
  },
];
